### ISSUE TITLE
Start script points to wrong directory

### ISSUE THREAD

**Issue by MrDeepPurple** [hopandfork/jgnuplot#4]
After compilation with maven, executable project is compiled inside ./target/classes folder. Starting script points to ./classes folder

**Comment by grussorusso** [comment]
The correct way to start the project is now building it using Maven, as stated in the README, and then launch the runnable JAR. Luca is now updating the `./jgp` script. However, that script is not much portable. We should consider distributing the application through packages for main Linux distributions.
